### ISSUE TITLE
Polystat link doesn't work

### ISSUE THREAD

**Issue by strogiyotec** [yegor256/yegor256#2]
link to Polystat doesn't work . Most probably because repo is private or was moved to another domain

**Comment by aleksandr-kotlyar** [comment]
Today it works. Think it solved 9 days ago https://github.com/yegor256/yegor256/commit/297bc9c613d2f771f0cfac08004d4730870821ad.

**Comment by yegor256** [comment]
@aleksandr-kotlyar solved, thanks
